# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
email: zzhou22@mgh.harvard.edu
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zzstefan.github.io/" # the base hostname & protocol for your site
twitter_username: ZhenZhou_1993
github_username:  zzstefan

# Build settings
markdown: kramdown
highlighter: rouge
